// export const test = async () => {

//     try {

//     } catch (error) {
//         console.error("Error in test function:", error);
//     }
// };
